### PR TITLE
match new API of serialport-rs 2.0.0

### PR DESCRIPTION
**Pull request by ndusart**
Prepare the changes to be made to use the next release of `serialport-rs`:

* `termios` crate was replaced by `nix`, so replacing it here as well
* `libc` is taken from `nix` crate, it avoid to use a different version than what `nix` is using.
* `available_baud_rates` is removed  in favor of `BaudRate::platform_rates()` so removing the `pub use`
* defined a new `Result` and `Error` type (just reexporting the ones from `serialport-rs`), it's for having some conversion trait for `nix::Error` since we're using `nix` now and termios functions returns this kind of error instead of `io::Error`

The downside is that `Cargo.toml` is now referencing git repositories instead of published versions.
Maybe you'll want to wait for the release of `serialport-rs` before merging.

### CODE REVIEW

**Comment by berkowski** [comment]
Good to see serialport-rs is chugging along nicely.   I'm traveling around for the next few days and will check out the PR once settled again

**Comment by berkowski** [comment]
Alright, I've had some time finally to look at this.  Thanks for the PR!

Switching over to `nix` raises some new issues on a few build targets, and the current head `serialport-rs` seems to have some issues on OSX itself.  Because of that I'd like to have your changes pushed to a new working branch (which I'll create) if that's OK with you.  Once the `nix` and `serialport-rs` issues are resolved we can have a clean merge back onto master.

**Comment by ndusart** [comment]
Of course we can push these changes into a new branch.

The breakages seem to be:
 - for OSX 32 bits: https://github.com/dcuddeback/iokit-sys/blob/master/src/types.rs is missing some use statement for `vm_address_t` (I do not know where these should come from) and `mach_vm_size_t`
- for OSX 64 bits (and probably 32 bits as well): it is certainly that version of libc taken by nix (from github) does not match with the one taken by IOKit-sys (from crates.io), hence the mismatch in types
- for BSD platforms, `nix::poll` is not available in all platforms, it's pretty close to be fixed as you saw when opening your PR there.

**Comment by berkowski** [comment]
Great.  And thanks for your work on all the upstream crates like `nix` and `libc`!  Please switch your PR target to the new `serialport-2` branch and we'll go from there.

**Comment by berkowski** [comment]
`freebsd` targets are now passing since your nix-rust/nix#672 was accepted, so that's one down.  I'm going to go ahead and merge this.  Thanks!

**Pull request merged**
