### PR TITLE
Windows implementation

### PR DESCRIPTION
**Pull request by ndusart**
This add support for Windows platform.

I used the [`mio-named-pipes`](https://github.com/alexcrichton/mio-named-pipes) crate to implement that easily without having to copy files from `mio` to use structs that are not public.

As its name implie, this crate allow to read/write to a named pipe which is basically implemented using `ReadFile`/`WriteFile` api just as what we have to use for COM ports.
The only difference reside in the way to create that file which is then handled specifically in `Serial::from_path`.

This is based on `serialport-2` branch as we need a new function (not merged yet) to create a `COMPort` with a handle directly. Allowing to open the file for asynchronous operations.
I'll have to switch to the crates.io serialport when published.

I modified the example to build on Windows too.
As async API is completion-based on Windows, readiness is actually updated only when `read` is actually performed. so we got a lot of `"Read would have blocked."` in the output as it is readable even if no bytes are available. That's inherent to `mio`

### CODE REVIEW

**Comment by berkowski** [comment]
Well happy new-year!

I'll keep track of your progress on `serialport-rs`: https://gitlab.com/susurrus/serialport-rs/merge_requests/25.  When that goes through at least we can keep the `serialport-rs` git link pointed at the main repository.

I don't have any experience with rust on windows, so thank you very much for pushing the initiative along!

**Comment by Susurrus** [comment]
I just released 2.1 of `serialport-rs` to crates.io, so at least that part is done now.

**Comment by berkowski** [comment]
@ndusart Looks like the "examples/win_test.rs" isn't included?  Otherwise looks ready to go.

**Comment by ndusart** [comment]
Is it ok if I just edit the existing example to build for Windows ?

**Comment by ndusart** [comment]
Ha sorry, I see what you mean the Cargo.toml is wrong. I'll fix it.

**Comment by ndusart** [comment]
I removed the example reference in Cargo.toml.
It was a basic test I made when testing my implementation.

**Pull request merged**
