### PR TITLE
Fix changelog

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by lnicola** [comment]
That Travis failure is...

```
$ ll target/x86_64-unknown-linux-musl/debug/test_unix-b207738c2b1e5e9f
target/x86_64-unknown-linux-musl/debug/test_unix-b207738c2b1e5e9f
$ target/x86_64-unknown-linux-musl/debug/test_unix-b207738c2b1e5e9f
zsh: command not found: target/x86_64-unknown-linux-musl/debug/test_unix-b207738c2b1e5e9f
$ strace -f target/x86_64-unknown-linux-musl/debug/test_unix-b207738c2b1e5e9f     
execve("target/x86_64-unknown-linux-musl/debug/test_unix-b207738c2b1e5e9f", ["target/x86_64-unknown-linux-musl"...], 0x7ffcc9810f88 /* 58 vars */) = -1 ENOENT (No such file or directory)
```

:confused:

**Comment by lnicola** [comment]
```
$ cross test --target x86_64-unknown-linux-musl
[...]
$ ldd target/x86_64-unknown-linux-musl/debug/mio_serial-7c98f0c55a144be6
	not a dynamic executable
$ ldd target/x86_64-unknown-linux-musl/debug/test_unix-b207738c2b1e5e9f 
	linux-vdso.so.1 (0x00007fffac9e1000)
	libudev.so.1 => /usr/lib/libudev.so.1 (0x00007f6c1c391000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f6c1c173000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f6c1bdb7000)
	/lib/ld64.so.1 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f6c1c5af000)
```

So it looks like the integration test has an interpreter set to `/lib/ld64.so.1`, which is missing even from the Docker image.

**Comment by lnicola** [comment]
Maybe the issue is that it's linked to `libudev`, which brings in `glibc`?

**Comment by berkowski** [comment]
Working at sea at the moment; I'll check back in mid-may.

**Pull request closed without merging**
