### PR TITLE
implement try_clone from SerialPort trait

### PR DESCRIPTION
**Pull request by ndusart**
serialport-rs 2.3.0 added the method `try_clone` in the `SerialPort` trait

### CODE REVIEW

**Comment by ndusart** [comment]
ping @berkowski ?

**Comment by berkowski** [comment]
Yup, here.  Work's just been keeping me busy during the week to the point I don't want to think about code in my free time :)

Checking things now.

**Comment by ndusart** [comment]
I totally understand, sorry for being insistent. I had an issue someday that notification of a pull request wasn't sent without an explicit mention.

Thanks for the merge and enjoy your weekend !

**Comment by berkowski** [comment]
No worries about the ping!   Just glad someone is finding the crate useful.   Haven't had any chance to play with rust in my own projects for a while now.

**Pull request merged**
